fix: #97 Unused attributes in a component's config yaml are just ignored by Pydantic
Modalities/modalities pull request #134
Opened 2024-05-21 10:00 UTC by lllAlexanderlll

Implemented verification that all required attributes are set and not more than optional + required attributes are present.
The does not use Pydantics verification methods, but implements the check in native python. This allows for a very clear error message about the configuration. 

With this fix, the misconfigured config
```yaml
batch_progress_subscriber:
  component_key: progress_subscriber
  variant_key: rich
```
was fixed.

2024-05-28 15:41 UTC, le1nux requested changes
LGTM. :-) The only thing that is missing is unit testing for  `_assert_valid_config_keys`

2024-06-06 22:52 UTC, le1nux commented
@lllAlexanderlll any updates? :-)

2024-06-11 09:08 UTC, mali-git commented
> @lllAlexanderlll any updates? :-)

Please see 73f73b1f5d99965ef13f472ce8f1fba3460edc65 :)

2024-06-11 09:18 UTC, fromm-m approved these changes

2024-06-11 09:19 UTC, merged