New downstream eval
Modalities/modalities pull request #150
Opened 2024-06-11 13:02 UTC by mrudat-iais

- new endpoint that converts our model into a HF model

2024-06-20 09:59 UTC, mrudat-iais commented
Hi @fromm-m @le1nux ,

- class added that defines what is needed for the models to be evaluated by eval harness
- all merge conflicts are resolved
- all tests run through

Can one of you please review? Thanks!

2024-06-24 13:58 UTC, le1nux requested changes

2024-06-24 13:58 UTC, le1nux commented on src/modalities/models/huggingface_adapters/mamba_hf_adapter.py
> +class MambaHuggingFaceModelAdapterConfig(HuggingFaceModelAdapterConfig):
I looks like we could simplify this via e.g., 

```python
class MambaHuggingFaceModelAdapterConfig(HuggingFaceModelAdapterConfig, MambaLLMConfig):
    is_encoder_decoder: Literal[False] = False

```

2024-06-24 14:00 UTC, le1nux reviewed
Added a bunch of remarks mostly concerning code standards. I did not an exhaustive list of issues, so please also look into the remaining source files  for similar issues such as unused imports, missing type hints, lack of comments. Thanks! :-)

2024-06-25 12:44 UTC, mrudat-iais commented on src/modalities/checkpointing/checkpoint_conversion.py
> +        logging.info(f"Config\n{self.config_dict}")
why should we remove it?

2024-06-25 13:15 UTC, closed without merging