added support for using multiple losses and metrics in evaluator
Modalities/modalities pull request #8
Opened 2024-01-15 15:32 UTC by BlueCrescent

2024-01-16 15:27 UTC, rrutmann commented on tests/test_evaluator.py
>          data_loaders=[llm_data_loader_mock],
Might make sense to add a test for multiple data_loaders

2024-01-16 15:32 UTC, rrutmann commented on src/modalities/gym.py
> +            loss_functions=[self.loss_fun],
Here we assume only one loss function. Where are multiple losses handled?

2024-01-18 11:17 UTC, le1nux requested changes
I like the structure of the code and the introduction of small functions. Helps reading the code a lot! 

I was thinking about the next steps for the metrics and losses. They should be configurable by the config and assembled dynamically.

2024-01-31 18:46 UTC, le1nux commented
Is this PR finalised and ready for review?

2024-02-05 08:06 UTC, BlueCrescent commented on tests/test_evaluator.py
> +    assert loss_mock.call_count == 4 * 2
Resolved in current version.

2024-02-05 08:07 UTC, BlueCrescent commented on tests/test_evaluator.py
> +def test_evaluate_calls_all_metrics(
Resolved in current version.

2024-02-18 21:36 UTC, BlueCrescent commented on src/modalities/loss_functions.py
> +    def __init__(self, target_key: str, prediction_key: str, tag: str = "CLMCrossEntropyLoss", reduction: str = "sum"):
I think, we should set this reduction to mean. Even, if that means that the loss aggregation for logging purposes gets a bit wonky.
Suddenly switching to sum here will have unforeseen effects on model training. This is probably equivalent to multiplying the learning rate with batch_size * max_sequence_length.

2024-03-11 22:53 UTC, le1nux reviewed
Really good work on the evaluation/aggregation part. I left a bunch of comments (some minor and some that would need some discussion). Primarily, I'm not so much convinced about the metric and loss factories that get instantiated on a very low level. I would  prefer if the instantiation would completely happen in the hierarchical instantiation and that these aggregated measures (instead of the factories) would be passed to the evaluator. I think that's the main point that necessitates discussion and I would like to hear your thoughts on it :-) 

FYI,  I did not take a look at the tests yet and wanted to add my comments already, as I think they would be helpful already.

2024-03-11 22:53 UTC, le1nux commented on src/modalities/evaluator.py
> +        return {loss: loss.compute() for loss in losses}, {metric: metric.compute() for metric in metrics}
maybe it makes sense to simplify losses and metrics just as measures? Maybe we can find a better word even?

2024-03-11 22:53 UTC, le1nux commented on src/modalities/evaluator.py
> +        return {loss: loss.compute() for loss in losses}, {metric: metric.compute() for metric in metrics}
Also, what about replacing `compute` with `aggregate`?

2024-03-11 22:53 UTC, le1nux commented on src/modalities/evaluator.py
> +        losses = [f.create(self.local_rank) for f in self._loss_factories]
not a big fan of the factories here, as they seem a bit overengineered. 
How about we instantiate the aggregated measures already in the hierarchical instantiation and pass the measures to the evaluator in main?
We could implement a `reset` function for all measures that clears out their internal state. In this case, we could get rid of the factories here, right?

2024-03-11 22:53 UTC, le1nux commented on src/modalities/evaluator.py
> +    if data_loader.batch_size is not None and data_loader.drop_last:
In `LLMDataLoader` the `batch_size` is never `None`.

2024-03-11 22:53 UTC, le1nux commented on src/modalities/evaluation/throughput_aggregator.py
> +        throughput_aggregator_factory: Callable[[], ThroughputAggregator] = ThroughputAggregator,
Could we pass in the aggregator directly? The `reset` function is implmented already.

2024-03-11 22:53 UTC, le1nux commented on src/modalities/evaluation/perplexity.py
> +    def create(self, local_rank: int) -> AggregativeMeasure[PerplexityKeys]:
as mentioned earlier, I think the factories are overkill.

2024-03-15 14:33 UTC, BlueCrescent commented on src/modalities/trainer.py
> +        for thoughput_aggregator, (batch_id, batch) in start_throughput_measurement(
I adapted this to use the context manager and not the weird iterable decorator anymore.

2024-06-11 09:36 UTC, closed without merging